# Generated by Django 4.0.4 on 2023-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Framework', '0002_category_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
