# Generated by Django 4.0.4 on 2023-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Framework', '0003_remove_student_father_name_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
